### ISSUE TITLE
Minimum network.txt headers required

### ISSUE THREAD

**Issue by susheelbhanu** [InaMariaDeutschmann/EnDED#1]
Hi @InaMariaDeutschmann, 

Thank you for a great tool. I'm interested in using this, but the headers in *my* `network.txt` do not match the example you have provided. I currently have two columns with the nodes, i.e. from and to, and then a correlation coefficient with a plus/minus sign.

So, could you please let me know what the minimum requirements in terms of headers and which columns are absolutely needed?

For example, I usually use `igraph`, so which of the below formats would be similar to what you have in your example file?
```
write_graph(graph, file, format = c("edgelist", "pajek", "ncol", "lgl",
  "graphml", "dimacs", "gml", "dot", "leda"), ...)
```

Thank you!

**Comment by InaMariaDeutschmann** [comment]
Thank you @susheelbhanu for your message.

Minimum requirement is to
- chose at least one method depending the method different data is needed, e.g., if you choose only Sign Pattern, you will need 1 column with association strength (correlation)
- If you have more columns and need to tell the program in which column to find the information that can be done with different options (also the two columns for the nodes can be changes)
- by default the environmental parameter will be searched for using the string "ENV", thus the names need to contain "ENV". If you used another string, this can also be changed

Let me know if you have more questions. If for any reason it doesn't work, please share a little example (or header) of the files and the command used to run EnDED.

Regarding igraph. I usually used the edgelist format.

Best,
Ina

**Comment by susheelbhanu** [comment]
@InaMariaDeutschmann thank you very much for the thorough explanation. I will give this a try in the coming week and may get back to you with an example should I run into issues. 

Best regards and thanks again!
