### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by choon-sim** [InaMariaDeutschmann/EnDED#2]
Hi,
thanks for making this useful tool. 

I have difficulty installing the program. I first created a conda environment to install python=3.7, gcc=11.2.0 and boost=1.77.0. Then I git cloned the EnDED folder, went inside the folder and type `make`. But there is an error.

```
(EnDED) server:~/EnDED$ make
g++  -o build/EnDED -lpthread
/usr/bin/ld: cannot open output file build/EnDED: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:17: recipe for target 'build/EnDED' failed
make: *** [build/EnDED] Error 1
```
If I manually created an empty subfolder `build/EnDED` and then typed `make`, I see this message:
`make: 'build/EnDED' is up to date.`
even though there is no file inside `build/EnDED`.

Any thought on this? =)

**Comment by InaMariaDeutschmann** [comment]
Hi choon-sim

Thank you for your interest in EnDED and for reaching out regarding this bug. Indeed there is a conflict caused by the additional c++ file I provided for evaluation proposes. After moving it to a subfolder, there should be no problem.

Let me know if this solved the installation issue.

Best regards,
Ina

**Comment by choon-sim** [comment]
Hi @InaMariaDeutschmann,

the installation now works beautifully.

On a separate note, in the vignette, the command to run the test data needs a minor fix to add `test_data` in front of the input and output files. For example:

`./build/EnDED --input_network_file test_data/Input/network.txt --methods SP,OL,II,DPI,CO --SP_colnum_interaction_score 3 --OL_colnum_interactionlength_startX_startY 8,6,7 --II_DPI_abundance_file test_data/Input/ID_abundance.txt --II_DPI_ENVparameter_file test_data/Input/ENV_parameters.txt --output_network_file test_data/Output/extended_network.txt --output_triplet_info test_data/Output/triplet_info.txt --output_discretized_vectors test_data/Output/disc_vectors.txt --do_pre_jointP_comp --II_permutation_iteration 100`

Also, it's probably trivial but the output folder must be manually created prior to the run. Otherwise the run will proceed without an error message, but the output files will not be created.
